import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "../lib/providers";

import { Toaster } from "react-hot-toast";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <div className='bg-gradient-to-b bg-gray-100 dark:from-gray-900 dark:to-gray-950'>
          <Providers>
            <Header />
            {children}
            <Footer />
            <Toaster />
          </Providers>
        </div>
      </body>
    </html>
  );
}
